export const AUTH_FETCH_ACCOUNT_FAILED_ERROR = "AUTH_FETCH_ACCOUNT_FAILED";
export const AUTH_ACCOUNT_NOT_FOUND_ERROR = "AUTH_ACCOUNT_NOT_FOUND";
export const AUTH_LOGIN_FAILED_ERROR = "AUTH_LOGIN_FAILED";
export const AUTH_NO_TOKEN_RECEIVED_ERROR = "AUTH_NO_TOKEN_RECEIVED";
export const AUTH_EMPTY_TOKEN_ERROR = "AUTH_EMPTY_TOKEN";
export const AUTH_REGISTER_FAILED_ERROR = "AUTH_REGISTER_FAILED";
export const AUTH_GOOGLE_LOGIN_FAILED_ERROR = "AUTH_GOOGLE_LOGIN_FAILED";
export const AUTH_GOOGLE_ID_TOKEN_MISSING_ERROR =
  "AUTH_GOOGLE_ID_TOKEN_MISSING";
export const PROFILE_FETCH_FAILED_ERROR = "PROFILE_FETCH_FAILED";

export type AppErrorCode =
  | typeof AUTH_FETCH_ACCOUNT_FAILED_ERROR
  | typeof AUTH_ACCOUNT_NOT_FOUND_ERROR
  | typeof AUTH_LOGIN_FAILED_ERROR
  | typeof AUTH_NO_TOKEN_RECEIVED_ERROR
  | typeof AUTH_EMPTY_TOKEN_ERROR
  | typeof AUTH_REGISTER_FAILED_ERROR
  | typeof AUTH_GOOGLE_LOGIN_FAILED_ERROR
  | typeof AUTH_GOOGLE_ID_TOKEN_MISSING_ERROR
  | typeof PROFILE_FETCH_FAILED_ERROR;
